[package]
name = "zensend"
version = "0.0.1"

[dependencies]
rustc-serialize = "0.3"
hyper = "0.7.0"
[dependencies.url]
git = "https://github.com/servo/rust-url"

[dev-dependencies]
yup-hyper-mock = "*"
log = "*" 
matches = "0.1.2"
